### PR TITLE
added_new_file_with_color_text

### PR DESCRIPTION
**Pull request by Pon20995**
- installed chalk package
- added new file with colorful text

### CODE REVIEW

**Review by Densf2 — CHANGES_REQUESTED** [review]
don't add node_modules directory from PR.
please remove

**Comment by Pon20995** [comment]
@Densf2 Do we need to install node_modules from the main branch?

**Comment by Densf2** [comment]
it is possible to install all packages from packages jsons file in any branch, not only main.
and each person who want use your code - just clone repo and install packages from package.json & package-lock.json files

**Comment by Pon20995** [comment]
@Densf2 The node_modules is removed from PR. Can I merge now? Thank you!

**Review by Densf2 — APPROVED** [review]
perfect.  looks good to me.

**Pull request merged**
